apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercise-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercise-app
  template:
    metadata:
      labels:
        app: exercise-app
    spec:
      containers:
        - name: exercise-app
          image: exercise-app:latest    # 로컬 이미지 사용
          imagePullPolicy: Never        # ← 중요! (로컬 이미지 쓰기 위해 필요)
          ports:
            - containerPort: 5173
